### ISSUE TITLE
ANSI vs UTF-8

### ISSUE THREAD

**Issue by Mistadouf** [rt-2/CZUL-Scope-Files#10]
GitHub semble fonctionner en UTF-8 mais Euroscope lit le fichier (dans mon cas Alias) comme du ANSI. Les lettres avec accent et les apostrophes sont mal interprétées par Euroscope.

**Comment by rt-2** [comment]
Bon j'ai regler ca (ca me prend 2 sec chui habituer moi les UTF8, Visual Studio REFUSE de créer les fichiers en UTF8 par default et ne peut meme pas les enregistrer en UTF8 sans un plugin lol).
https://github.com/rt-2/CZUL-Scope-Files/commit/0c272e80aead558c395cc2c579db60614ea3dae6

**Comment by rt-2** [comment]
Je crois qu'on peut fermer ce issue
