### ISSUE TITLE
CZUL-CZYZ North Gate

### ISSUE THREAD

**Issue by Mistadouf** [rt-2/CZUL-Scope-Files#119]
On devrait aller ajouter la North Gate avec CZYZ dans le sector file

**Comment by rt-2** [comment]
Is that it?
file: CZUL.ese Lines 1650-1661 
https://github.com/rt-2/CZUL-Scope-Files/blob/master/CANscope/CZUL/CZUL.ese#L1650-L1661

**Comment by rt-2** [comment]
Marked as bug because technicly is 'must' be there since its in our LOA with czyz and we are expected to hand them aircrafts in this zone

**Comment by Mistadouf** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/164
