### ISSUE TITLE
Remove all ceilings

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#125]

**Comment by Mistadouf** [comment]
user can set a ceiling, but should not enable by default, except for ground files

**Comment by rt-2** [comment]
Yes actually I talked to P-L about it the other day, since then I agree that we might want to remove them all instead.

**Comment by rt-2** [comment]
Since it's low importance I think we should get more people's opinion.

**Comment by rt-2** [comment]
For realism, no scopes should have any ceilings.
Scopes to check:

- [ ] CTRs
- [ ] APPs
- [ ] TWRs
- [ ] GNDs

**Comment by rt-2** [comment]
I checked CTRs, they have no ceilings

**Comment by rt-2** [comment]
Answer from someone at NavCanada, no radars have ceiilings, not even the TWR one

**Comment by rt-2** [comment]
There is no ceilings anywhere (have not checked ground)
