### ISSUE TITLE
CYOW ground differences (taxiway M & P (corner up-left), etc)

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#128]
![image](https://user-images.githubusercontent.com/3452428/54724855-3bd1ad80-4b43-11e9-9fdc-34b6a526c021.png)

**Comment by Mistadouf** [comment]
ground layout de CYOW à refaire pour matcher le style de CYUL et CYQB

**Comment by rt-2** [comment]
I found the problem xD
![image](https://user-images.githubusercontent.com/3452428/65839420-62835480-e2db-11e9-834b-097bc8b58791.png)

**Comment by rt-2** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/237 will fix

**Comment by rt-2** [comment]
![image](https://user-images.githubusercontent.com/3452428/65839663-762fba80-e2dd-11e9-8ed9-7e97c5f69520.png)
![Feels_good](https://user-images.githubusercontent.com/3452428/65839669-86479a00-e2dd-11e9-92d2-0ee756309d19.png)

**Comment by rt-2** [comment]
Continuing with https://github.com/rt-2/CZUL-Scope-Files/issues/250

**Comment by rt-2** [comment]
#250 is closed
