### ISSUE TITLE
Auto text messages

### ISSUE THREAD

**Issue by Mistadouf** [rt-2/CZUL-Scope-Files#136]
modifier les messages textes automatiques dans l'alias

**Comment by rt-2** [comment]
Quel?
Référence?
(click sur le numero de ligne dans github pour avoir un url qui pointe cette ligne)
ex: https://github.com/rt-2/CZUL-Scope-Files/blob/master/CANscope/CZUL.prf#L2

**Comment by rt-2** [comment]
still relevant?

**Comment by Mistadouf** [comment]
#182
