### ISSUE TITLE
 Modernised EuroScope Sound Set

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#14]
The set contains replacement files for all 20 of Euroscope's vanilla sounds. The sounds were designed to be more modern and intuitive to the controller's ear, and less irritating to the eardrum :P.

original link: https://www.vatcan.ca/forums/index.php?topic=6272.0

- [ ] Check what is ultimately more realistic
- [ ] Compatibility
- [ ] Making sure there no sounds left?

**Comment by rt-2** [comment]
link to original post updated

**Comment by Mistadouf** [comment]
Will leave the choice to the controller
