### ISSUE TITLE
Espace non-contrôlé

### ISSUE THREAD

**Issue by Mistadouf** [rt-2/CZUL-Scope-Files#177]
ajouter les lignes délimitant l'espace aérien contrôlé et non-contrôlé

**Comment by rt-2** [comment]
![image](https://user-images.githubusercontent.com/3452428/56852860-59d2c080-68ee-11e9-8133-d8485ef0e407.png)
This is from Toronto

**Comment by Mistadouf** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/315
