### ISSUE TITLE
Moncton ZV sector boundaries missing

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#191]
![image](https://user-images.githubusercontent.com/3452428/57641524-38770300-7583-11e9-81b0-e57eb517f74f.png)

**Comment by rt-2** [comment]
Actually we control there when Moncton is not connected, we need something better.
Actually a bug

**Comment by rt-2** [comment]
I need that its my eastern limit when I control High Moncton lol!

**Comment by rt-2** [comment]
Lines are there and they are incomplete/confusing

**Comment by Mistadouf** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/305/commits/f92a28718fb66524e08f1ac3eb451af40e5a8e69
