### ISSUE TITLE
must add AFV plugin

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#241]

**Comment by rt-2** [comment]
as of 2019-10-30

**Comment by rt-2** [comment]
https://github.com/rt-2/CZUL-Scope-Files/tree/AFV-Update

**Comment by Mistadouf** [comment]
AFV bridge?, it only adds freq for text traffic. I believe text only traffic should be kept on primary freq, not on multi freq. This now becomes unnecessary.

**Comment by rt-2** [comment]
Actually what I was talking about is the settings, but this have been done in the pass so yes, should close this
