### ISSUE TITLE
MTL_CTR double texts

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#248]
Basically MTL_CTR will activate both CTR and RW_CTR in the voice comms, Result is double texts when sending messages to pilots.

**Comment by rt-2** [comment]
After 1-2h it comes back :(

**Comment by Mistadouf** [comment]
bug with AFV bridge

**Comment by Mistadouf** [comment]
AFV bridge will assign all freq, including double, nothing we can do on our side.
