### ISSUE TITLE
m_AseURL setting URL 404

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#267]
https://github.com/rt-2/CZUL-Scope-Files/blob/master/CANscope/CZUL/CZUL%20General%20settings.txt#L107

The url respond a 404.

What is the purpose of `m_AseURL` ?

Should we fix this?

**Comment by Mistadouf** [comment]
No clue

**Comment by rt-2** [comment]
Im pretty sure THIS fixed it (added to beta 3.2.1.24)
![image](https://user-images.githubusercontent.com/3452428/89708664-f2a41880-d946-11ea-953d-3ab662bbaa61.png)
Will reopen if problem is seen again
