### ISSUE TITLE
maybe integrated teamspeak client

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#268]
There is functions for connecting to TS, can we use them maybe?

https://github.com/rt-2/CZUL-Scope-Files/blob/master/CANscope/CZUL/CZUL%20General%20settings.txt#L143

**Comment by chrissKLO** [comment]
The TS3 server would ideally be for the integrated VCCS system with the most up-to-date beta of Euroscope. The TS server though needs to be specifically configured for this if I'm not mistaken. A server that everybody uses at the moment is `vatsim-scandinavia.org`

**Comment by Mistadouf** [comment]
will not do, TS outside is enough for now, and AFV should implement Landline
