### ISSUE TITLE
CYMX Sectors hiding CYR

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#282]
CYMX_EXT1 should be renamed to West, 2-> east.
Also, those and CYMX TWR when ativated, they hide the CYR
![image](https://user-images.githubusercontent.com/3452428/73612725-22e7b480-45bc-11ea-82c0-d99c705fe9a7.png)

**Comment by Mistadouf** [comment]
![Annotation 2020-02-02 183117](https://user-images.githubusercontent.com/48373353/73617225-432e6800-45ea-11ea-8499-5235f79fd9d8.jpg)

**Comment by Mistadouf** [comment]
CYR isn't hidden for me

**Comment by rt-2** [comment]
Do you have the sector ownership layers enabled?

**Comment by rt-2** [comment]
Issue confirmed after deleting the CZUL folder from canscope and redownloading the last version.
![image](https://user-images.githubusercontent.com/3452428/75338722-2ee23180-585d-11ea-807c-8fe2e6d072bb.png)

**Comment by Mistadouf** [comment]
![image](https://user-images.githubusercontent.com/48373353/75797822-b3dcb780-5d43-11ea-8e36-baca3c10994a.png)
![image](https://user-images.githubusercontent.com/48373353/75797892-cbb43b80-5d43-11ea-9129-971b64ae7316.png)
Did a clean install of Euroscope, Canscope and sector files and no issue on my side

**Comment by rt-2** [comment]
we're gonna have to check with a 3rd party

**Comment by Mistadouf** [comment]
How do you check on your side? How can I reproduce the issue?

**Comment by rt-2** [comment]
The steps to reproduce:
-Open CTR_LO;
-in display setting, enable the "active sector" for "cymx_twr"
Part of the CYR should be hidden

**Comment by Mistadouf** [comment]
![image](https://user-images.githubusercontent.com/48373353/77108567-d1bf4300-69f8-11ea-8046-a7a35621a2f5.png)
Able to reproduce problem as described, would not consider a bug as it is not hidden when position is connected normally. Probably has to do with the drawing priority/order of Euroscope.

**Comment by Mistadouf** [comment]
Planning to redo CYR/CYA in near future so will chack at the same time

**Comment by rt-2** [comment]
Im not home but if you do the same thing with the RW sector the Lac Saint
Pierre CYR should be hidden in this case.

**Comment by rt-2** [comment]
FALSE POSITIVE
