### ISSUE TITLE
Missing FIR boundarie between the 2 CZQX airspaces

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#285]
![image](https://user-images.githubusercontent.com/3452428/75333835-d444d780-5854-11ea-8b6a-1a2d5ec45e31.png)
![image](https://user-images.githubusercontent.com/3452428/75333951-048c7600-5855-11ea-8a5b-6377f7e5a324.png)

**Comment by Mistadouf** [comment]
![image](https://user-images.githubusercontent.com/48373353/75836364-acdb9680-5d8f-11ea-913d-cc2570fdbe96.png)
Like this is good?

**Comment by rt-2** [comment]
Should be perfect,
C'était juste pour enlever les ambiguités pour un handoff, savoir à qui envoyer. 
Merci

**Comment by Mistadouf** [comment]
done

**Comment by rt-2** [comment]
reference to when/where it was fixed?

**Comment by Mistadouf** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/305/commits/f92a28718fb66524e08f1ac3eb451af40e5a8e69

**Comment by rt-2** [comment]
https://github.com/rt-2/CZUL-Scope-Files/pull/305/commits/f92a28718fb66524e08f1ac3eb451af40e5a8e69
