### ISSUE TITLE
Link to soundset is not working

### ISSUE THREAD

**Issue by sandpatch** [rt-2/CZUL-Scope-Files#314]
As the tile says, minor problem but I can not download the modernised sound set.

**Comment by rt-2** [comment]
It is not something we currently use.
I updated the link in the original post (https://github.com/rt-2/CZUL-Scope-Files/issues/14)
You need to post a message on the forum asking for an update to Andrew Ogden because the link is broken in his original post.
Good luck.
Thanks

**Comment by sandpatch** [comment]
It is available via gander oceanic now. Link: https://ganderoceanic.com/eurosounds

Thanks for the help.
