### ISSUE TITLE
STAR assigned to aircrafts without a STAR in FP

### ISSUE THREAD

**Issue by rt-2** [rt-2/CZUL-Scope-Files#349]
![image](https://user-images.githubusercontent.com/3452428/99147824-f0421080-2651-11eb-85f4-1aac6a752072.png)

**Comment by Mistadouf** [comment]
As discussed in this thread: https://forums.vatsim.net/topic/8379-star-and-routing/
ES automatically selects the first STAR matching waypoint and rwy.

**Comment by Mistadouf** [comment]
Not a bug, just ES feature

**Comment by Mistadouf** [comment]
Also mentioned in the ES user manual

**Comment by rt-2** [comment]
ok @Mistadouf Thank you for the information.
Closed because unfixable.
